sudo: required
services:
  - docker

before_install: 
  - docker build -t bryantto08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bryantto08/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-docker-react"
  env: "Udemy-docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-088690727807"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"